### ISSUE TITLE
interpreter ro ezafe kardam !

### ISSUE THREAD

**Issue by arash-khajelou** [omiddavoodi/MEIL#1]
hala bayad biaim tu interpreter plug-in ezafe konim ! 
masalan age mikhaim if ro befahme ! ye if.h o if.cpp doros mikonim , k tu interpreter be mahze inke if tashkhis dade beshe ! string ro mifrestim be if ;)
ok e ?

**Comment by kharazi** [comment]
فکر کن خدای نکرده زبونم لال دو فردا دیگه یکی بیاد اینو بخونه بخاد بفهمه چیکار کردی!!!:دی
به چه زبونیه اینا

https://github.com/facebook/FBMock/issues?page=1&state=closed
